### ISSUE TITLE
Widget Attributes such as Key not being passed into <Widget /> 

### ISSUE THREAD

**Issue by roshaans** [NearSocial/VM#127]
In the VM we create an attribute key like below, but we do not seem to be passing it to `<Widget/>` properly.
```
attributes.key = `${this.vm.widgetSrc}-${element}-${this.vm.gIndex}`
```

In this snippet of code at this [line](https://github.com/NearSocial/VM/blob/a6ed652ff5ea296321e8a0eba09239da160cfa7b/src/lib/vm/vm.js#L635),  I can see that we are passing all the attributes to the <Widget/> component but when I add log statements inside of the `<Widget/>` component, I do not seem to get a key from the props or forwarded Props. 

``` components/Widget.js

export const Widget = React.forwardRef((props, forwardedRef) => {
  const {
    loading,
    src: propsSrc,
    code: propsCode,
    depth,
    config: propsConfig,
    props: propsProps,
    ...forwardedProps
  } = props;

  console.log("widgetProps", props);
  console.log("forwardedProps", forewardedProps);
  //  Both of these logs do not contain the attribute.key

```

For a sanity check, I added a log statement where we return `<Widget/>` [from the VM](https://github.com/NearSocial/VM/blob/a6ed652ff5ea296321e8a0eba09239da160cfa7b/src/lib/vm/vm.js#L635) and we seem to be passing the key correctly: 
```
    } else if (element === "Widget") {
      console.log("widget attributes", attributes.key)
      return <Widget {...attributes} />;
```

### What is my usecase?

Widgets often times are composed of multiple widgets but currently it is hard to tell what is composed of what. 

I would like to be able to see the `key` attribute through Chrome Browser dev console when using the **Inspect Element** feature. It will show me the Widget Src responsible for rendering the HTML on the   DOM visually. 

I would like to create an extension similar to `inspect-element` which allows the user to browse the dom and see which `widgets` are responsible for rendering the given HTML elements.

**Comment by evgenykuzyakov** [comment]
`key` is a react property to differentiate elements within a single parent and decide which elements need to rerender. https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key
