### ISSUE TITLE
VM.require method drops "Cannot read properties of undefined (reading 'rawCode')" error

### ISSUE THREAD

**Issue by matiasberaldo** [NearSocial/VM#137]
### Problem
There's an issue with the `VM.require` method which drops the following error:
<img width="935" alt="image" src="https://github.com/NearSocial/VM/assets/47929792/97f8bc1f-2da6-4d2d-b953-11b7e1edf3c7">

The components loaded using the VM.require method are stateless, and the parent component doesn't pass any state property to the components loaded by VM.require.

### Steps to reproduce
There are different ways to reproduce this issue, even with common gateways such as Near.org, Near.Social and Jutsu.ai, but the following one is the easiest way to reproduce it:

1. Fork or use the following bOS components:

- Stateful Main Component: https://near.org/near/widget/ComponentDetailsPage?src=mattb.near/widget/Linktree.Main&tab=source
- Stateless Theme Component: https://near.org/near/widget/ComponentDetailsPage?src=mattb.near/widget/Linktree.Themes.Default&tab=source
- Stateless SDK Component: https://near.org/near/widget/ComponentDetailsPage?src=mattb.near/widget/Linktree.Utils.SDK&tab=source

2. Fork the Polygon Gateway: https://github.com/NearDeFi/polygon-bos-gateway
3. Replace the VM component link under `src/components/polygon/index.tsx` to the Stateful Main Component forked or use the same as step 1 (mattb.near/widget/Linktree.Main).
4. Deploy the gateway using Vercel
5. The gateway drops the error: Cannot read properties of undefined (reading 'rawCode')

### Live example
You can check a live example of the error in the following [link](https://linktree-bos.vercel.app/).

**Comment by evgenykuzyakov** [comment]
Please update the VM dependency from `near-social-vm": "github:NearSocial/VM#2.2.3"` to `near-social-vm": "github:NearSocial/VM#2.4.2"`

**Comment by matiasberaldo** [comment]
Hello @evgenykuzyakov 

Yes, looks like updating to the latest version (2.4.2) the issue has been solved.

Thank you so much for your support and time
