### ISSUE TITLE
Support multiple Limited Access Keys on BOS gateway to enable "Don't ask me again" when interacting with thirdparty contracts on BOS

### ISSUE THREAD

**Issue by frol** [NearSocial/VM#148]
**Is your feature request related to a problem? Please describe.**

Here is the video recording: https://www.loom.com/share/61e95ce27c004e93a4f4ef8dd15422c9

As a user of [DevHub](https://near.social/devgovgigs.near/widget/gigs-board.pages.Feed), I don't want to be bothered with signing every single interaction (like or post on DevHub). Since DevHub uses their own contract, BOS gateway cannot sign the function call with the limited access key it has for social.near, so it falls back to signing it with a full access key and redirects to the wallet.

**Describe the solution you'd like**

As a user, I should be prompted with "Don't ask me again" prompt on the first interaction just like the regular experience of BOS likes and posts on social.near, and that would add a new limited access key that would be able to sign the function calls to the DevHub contract.

This will also be needed for FastAuth-created accounts (https://github.com/near/fast-auth-signer/issues/97), but there is also a limitation of 4 access keys per zero-balance account, so access keys needs to be rotated somehow, I guess, but it is a different story...

**Comment by petersalomonsen** [comment]
I believe in order to achieve this, you need to add support for adding multiple function access keys in each wallet implementation in the wallet selector. Like what I've already started working on here: https://github.com/near/wallet-selector/pull/887/files#diff-a5f9f24a017d7cfc607d1374e5cb05560b792b8f93d15e13ae6a13a9b29f36a8R177

**Comment by petersalomonsen** [comment]
Thanks for the response @frol, and you are right. I had a quick chat with @evgenykuzyakov , and he is proposing a better solution which is about managing a keystore in the VM and using near-api-js directly for the transactions that use function access keys. Obtaining these function access keys will be through a transaction with the signed in wallet. So should be no work on the wallet selector then, I will try creating an MVP for this.

**Comment by frol** [comment]
Resolved in #156
