### ISSUE TITLE
Request `State.clear()`

### ISSUE THREAD

**Issue by idea404** [NearSocial/VM#2]
Currently to clear state we set variables within state to their initial values, e.g. `[]`. Would be nice to have a method belonging to `State` that can be invoked to perform the same functionality.

_Example_ 

```js
const writeStateTerm = (term) => {
  console.log("writeStateTerm:", term);

  State.update({
    term,
  });
  
  // we clear state whenever a clearing term is passed
  if (term === "") {
    State.update({
      post: [],
      comment: [],
      profile: [],
    });
  }
};
```

seen: https://github.com/near/near-search/blob/3d0b6bca4587177e90b63d85511332d45c83a242/widget/searchBar.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L13-L20

**Comment by evgenykuzyakov** [comment]
One option is to use `function` to clear the state. E.g. `State.update((state) => ({}))`.

Another option is to set `state` to empty object and then call `State.update`:
```js
state = {};
State.update();
```
